# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/lovinggauss: container
    io.kubernetes.cri-o.ContainerType/sillykeller: container
    io.kubernetes.cri-o.SandboxID/lovinggauss: 745deb259a5849fb40ee73a69aca7fceea401b4a17030f08cca05690b70424c
    io.kubernetes.cri-o.SandboxID/sillykeller: 745deb259a5849fb40ee73a69aca7fceea401b4a17030f08cca05690b70424c
    io.kubernetes.cri-o.TTY/lovinggauss: "false"
    io.kubernetes.cri-o.TTY/sillykeller: "false"
    io.podman.annotations.autoremove/lovinggauss: "FALSE"
    io.podman.annotations.autoremove/sillykeller: "FALSE"
    io.podman.annotations.init/lovinggauss: "FALSE"
    io.podman.annotations.init/sillykeller: "FALSE"
    io.podman.annotations.privileged/lovinggauss: "FALSE"
    io.podman.annotations.privileged/sillykeller: "FALSE"
    io.podman.annotations.publish-all/lovinggauss: "FALSE"
    io.podman.annotations.publish-all/sillykeller: "FALSE"
  creationTimestamp: "2022-12-30T12:49:50Z"
  labels:
    app: demowordpress
  name: demo_wordpress
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - apache2-foreground
    env:
    - name: WORDPRESS_DB_NAME
      value: wordpress
    - name: WORDPRESS_DB_HOST
      value: 127.0.0.1
    - name: WORDPRESS_DB_PASSWORD
      value: root
    - name: WORDPRESS_DB_USER
      value: root
    image: docker.io/library/wordpress:5.4.2-php7.2-apache
    name: sillykeller
    ports:
    - containerPort: 80
      hostPort: 8585
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/www/html
      name: 49a15df43433f1feb19b94777fa7f9ccacce78a89d056b2e0b1db396cf5a43da-pvc
  - args:
    - --default-authentication-plugin=mysql_native_password
    env:
    - name: MYSQL_DATABASE
      value: wordpress
    - name: MYSQL_ROOT_PASSWORD
      value: root
    image: docker.io/library/mysql:5.7
    name: lovinggauss
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: d3b73de13c7dab0d7e57fdf7ecc92736ebc0a71d9df35a0cd1925f170b1af541-pvc
  enableServiceLinks: false
  hostname: demo_wordpress
  restartPolicy: Never
  volumes:
  - name: 49a15df43433f1feb19b94777fa7f9ccacce78a89d056b2e0b1db396cf5a43da-pvc
    persistentVolumeClaim:
      claimName: 49a15df43433f1feb19b94777fa7f9ccacce78a89d056b2e0b1db396cf5a43da
  - name: d3b73de13c7dab0d7e57fdf7ecc92736ebc0a71d9df35a0cd1925f170b1af541-pvc
    persistentVolumeClaim:
      claimName: d3b73de13c7dab0d7e57fdf7ecc92736ebc0a71d9df35a0cd1925f170b1af541
status: {}

